name: Build and Deploy

on:
  push:
    tags:
      - auth-android@*.*.*
      - auth-ios@*.*.*
      - booking-android@*.*.*
      - booking-ios@*.*.*
      - dashboard-android@*.*.*
      - dashboard-ios@*.*.*
      - shopping-android@*.*.*
      - shopping-ios@*.*.*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Download a single artifact
      #   uses: actions/download-artifact@v3
      #   continue-on-error: true
      #   with:
      #     name: node-modules-cache

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # - name: Cache dependencies
      #   uses: actions/cache@v3
      #   with:
      #     path: .yarn/cache
      #     key: npm-${{ hashFiles('yarn.lock') }}
      #     restore-keys: npm-

      - name: Install dependencies
        run: |
          cd .yarn
          wget https://github.com/doiya46/super-app-showcase-origin/releases/download/cache%400.0.1/cache.zip
          unzip cache.zip
          rm -fr cache.zip
          cd ..
          yarn install --frozen-lockfile

      - name: Create code-signing.pem
        env:
          CODE_SIGNING_KEY: ${{ secrets.CODE_SIGNING_KEY }}
        run: echo "$CODE_SIGNING_KEY" > code-signing.pem

      - name: Build
        run: yarn node scripts/build-miniapp.js ${{ github.ref_name }}

      - name: Delete code-signing.pem
        run: rm code-signing.pem

      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: node-modules-cache
      #     retention-days: 30
      #     path: |
      #       .yarn/cache

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'build/**/*.bundle,build/**/*.map'
          artifactErrorsFailBuild: true
          skipIfReleaseExists: true
          name: ${{ github.ref_name }}
          tag: ${{ github.ref }}
